### ISSUE TITLE
Synchronize ot4i.github.io with GitHub repo

### ISSUE THREAD

**Issue by slachiewicz** [ot4i/ot4i.github.io#9]
I found that http://ot4i.github.io is out of sync with Github repo. 

In IBM Integration Toolkit was by default configured with urls to 
http://ot4i.github.io/iib-patterns/en/repo_metadata.json 
http://ot4i.github.io/iib-patterns/en/experimental/repo_metadata.json

Unfortunetly first will returns empty pattern list.

**Comment by hosie** [comment]
@slachiewicz This intentional.  The git hub repos are the source repositories for any work in progress.  The finished artifacts will only appear on the IIB toolkit list once the IIB team are satisfied that they are good enough quality to deliver to their users and decide to publish them there.

**Comment by slachiewicz** [comment]
ok. So for now - there is no pattern to use?
